---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Secutiry Check

#
# Documentation:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, main]

###############
# Set the Job #
###############
jobs:
  security:
    # Name the Job
    name: Secutiry Check
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Bandit checks
        # specify a path
        uses: jpetrucciani/bandit-check@master
        with:
          bandit_flags: '-r'